name: note_taking_firebase
description: Write notes with style.

publish_to: 'none'

version: 1.7.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.5.0
  dynamic_color: ^1.6.2
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^2.0.4
  provider: ^6.0.5
  quick_actions: ^1.0.2
  random_string_generator: ^2.0.0
  shared_preferences: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_quill: ^7.1.4
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_app_check: ^0.1.2
  google_sign_in: ^6.1.0
  google_mobile_ads: ^2.4.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  
  assets:
    - assets/