name: note_taking_firebase
description: Write notes with style.

publish_to: "none"

version: 1.9.3

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animations:
  awesome_snackbar_content:
  cloud_firestore:
  dynamic_color:
  firebase_app_check:
  firebase_auth:
  firebase_core:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_cache_manager:
  flutter_colorpicker:
  flutter_drawing_board:
  flutter_quill:
  get:
  google_mobile_ads:
  google_sign_in:
  provider:
  qr_code_dart_scan:
  qr_flutter:
  quick_actions:
  random_string_generator:
  share_plus:
  shared_preferences:
  restart_app:
  update_available:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
