name: note_taking_firebase
description: Write notes with style.

publish_to: "none"

version: 1.8.2+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animations: ^2.0.8
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.9.2
  dynamic_color: ^1.6.6
  firebase_app_check: ^0.2.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_drawing_board: ^0.5.0
  flutter_quill: ^7.4.6
  flutter_staggered_animations: ^1.1.1
  get: ^4.6.5
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  provider: ^6.0.5
  qr_code_dart_scan: ^0.7.2
  qr_flutter: ^4.1.0
  quick_actions: ^1.0.6
  random_string_generator: ^2.0.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
