name: note_taking_firebase
description: Write notes with style.

publish_to: 'none'

version: 1.4.1+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.2
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  google_sign_in: ^6.0.1
  provider: ^6.0.5
  flutter_svg: ^2.0.0+1
  cloud_firestore: ^4.3.2
  random_string_generator: ^2.0.0
  quick_actions: ^1.0.2
  flutter_quill: ^6.4.2
  shared_preferences: ^2.0.18
  firebase_app_check: ^0.1.1+13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  
  assets:
    - assets/