name: note_taking_firebase
description: Write notes with style.

publish_to: "none"

version: 1.9.2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.14.0
  dynamic_color: ^1.6.9
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_colorpicker: ^1.0.3
  flutter_drawing_board: ^0.7.0+2
  flutter_quill: ^9.3.5
  flutter_staggered_animations: ^1.1.1
  get: ^4.6.6
  google_mobile_ads: ^5.0.0
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  qr_code_dart_scan: ^0.7.3
  qr_flutter: ^4.1.0
  quick_actions: ^1.0.7
  random_string_generator: ^2.0.0
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  restart_app: ^1.2.1
  update_available: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
