name: note_taking_firebase
description: Write notes with style.

publish_to: 'none'

version: 1.8.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  cloud_firestore: ^4.7.0
  dynamic_color: ^1.6.3
  firebase_app_check: ^0.1.4
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  flutter_local_notifications: ^14.0.0+2
  flutter_quill: ^7.1.18
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.5
  get: ^4.6.5
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  quick_actions: ^1.0.3
  random_string_generator: ^2.0.0
  share_plus: ^7.0.0
  shared_preferences: ^2.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  
  assets:
    - assets/