name: note_taking_firebase
description: Write notes with style.

publish_to: 'none'

version: 1.7.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  cloud_firestore: ^4.5.2
  dynamic_color: ^1.6.3
  firebase_app_check: ^0.1.2+2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter_colorpicker: ^1.0.3
  flutter_quill: ^7.1.10
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.5
  google_mobile_ads: ^2.4.0
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  quick_actions: ^1.0.2
  random_string_generator: ^2.0.0
  shared_preferences: ^2.1.0
  get: ^4.6.5
  qr_flutter: ^4.0.0
  flutter_local_notifications: ^14.0.0
  timezone: ^0.9.2
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  
  assets:
    - assets/